[build]
# The index HTML file to drive the bundling process.
target = "manager.html"
# Build in release mode.
release = true
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
public_url = "/"

[watch]
# Paths to watch, defaults to build target parent folder.
path = ["src"]
# Paths to ignore.
ignore = []

[serve]
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = true

[clean]
# The output dir for all final assets.
dist = "dist"
# Optionally perform a cargo clean.
cargo = false
